apps:
  cbe:
    id: "com.commercialbankofethiopia.cbeapp"
    name: "Commercial Bank of Ethiopia"
  boa:
    id: "com.bankofabyssinia.boaapp"
    name: "Bank of Abyssinia"
  dashen:
    id: "com.dashenbank.dashenapp"
    name: "Dashen Bank"