apps:
  cbe:
    id: "com.combanketh.mobilebanking"
    name: "Commercial Bank of Ethiopia"
  boa:
    id: "com.boa.boaMobileBanking"
    name: "Bank of Abyssinia"
  dashen:
    id: "com.dashen.dashensuperapp"
    name: "Dashen Bank"